//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asto.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ASTOGelatoEntities : DbContext
    {
        public ASTOGelatoEntities()
            : base("name=ASTOGelatoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Banner_This> Banner_This { get; set; }
        public virtual DbSet<Blog_This> Blog_This { get; set; }
        public virtual DbSet<News_This> News_This { get; set; }
        public virtual DbSet<Product_Category> Product_Category { get; set; }
        public virtual DbSet<Product_Format> Product_Format { get; set; }
        public virtual DbSet<Product_This> Product_This { get; set; }
        public virtual DbSet<Store_Photo> Store_Photo { get; set; }
        public virtual DbSet<Store_This> Store_This { get; set; }
        public virtual DbSet<Log_This> Log_This { get; set; }
        public virtual DbSet<Order_Details> Order_Details { get; set; }
        public virtual DbSet<Order_This> Order_This { get; set; }
    }
}
