//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_This
    {
        public Order_This()
        {
            this.Order_Details = new HashSet<Order_Details>();
        }
    
        public string OT_ID { get; set; }
        public string Guest { get; set; }
        public string Phone { get; set; }
        public string Mail { get; set; }
        public string City { get; set; }
        public string District { get; set; }
        public string PostaCode { get; set; }
        public string Address { get; set; }
        public string InvoiceTitle { get; set; }
        public string UniformNumbers { get; set; }
        public string PayMethod { get; set; }
        public Nullable<System.DateTime> Datetime { get; set; }
        public string Preferential { get; set; }
        public Nullable<decimal> TotlePrice { get; set; }
        public string LastNumber { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> ShippingFee { get; set; }
        public string TrackingNumber { get; set; }
        public string ShippingStatus { get; set; }
        public string Remark { get; set; }
    
        public virtual ICollection<Order_Details> Order_Details { get; set; }
    }
}
