//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Format
    {
        public string PF_ID { get; set; }
        public string PT_ID { get; set; }
        public string Format { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> MPrice { get; set; }
        public Nullable<bool> BeOrder { get; set; }
        public Nullable<bool> Enable { get; set; }
    
        public virtual Product_This Product_This { get; set; }
    }
}
