//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store_This
    {
        public Store_This()
        {
            this.Store_Photo = new HashSet<Store_Photo>();
        }
    
        public int ST_ID { get; set; }
        public string ST_Name { get; set; }
        public string Introduct { get; set; }
    
        public virtual ICollection<Store_Photo> Store_Photo { get; set; }
    }
}
